# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/FPGA/VGA/zybo_petalinux/zybo_petalinux_vga/zybo_petalinux_vga.srcs/sources_1/bd/block_design/ip/block_design_auto_pc_1/block_design_auto_pc_1.xci
# IP: The module: 'block_design_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/VGA/zybo_petalinux/zybo_petalinux_vga/zybo_petalinux_vga.srcs/sources_1/bd/block_design/ip/block_design_auto_pc_1/block_design_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: h:/FPGA/VGA/zybo_petalinux/zybo_petalinux_vga/zybo_petalinux_vga.srcs/sources_1/bd/block_design/ip/block_design_auto_pc_1/block_design_auto_pc_1.xci
# IP: The module: 'block_design_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/VGA/zybo_petalinux/zybo_petalinux_vga/zybo_petalinux_vga.srcs/sources_1/bd/block_design/ip/block_design_auto_pc_1/block_design_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
