# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Projects/ZYBO_Master.xdc

# Block Designs: bd/block_design/block_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design || ORIG_REF_NAME==block_design} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_dispctrl_0_0/block_design_axi_dispctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_dispctrl_0_0 || ORIG_REF_NAME==block_design_axi_dispctrl_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_vdma_0_0/block_design_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_vdma_0_0 || ORIG_REF_NAME==block_design_axi_vdma_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_processing_system7_0_0/block_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_processing_system7_0_0 || ORIG_REF_NAME==block_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_interconnect_0_0/block_design_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_interconnect_0_0 || ORIG_REF_NAME==block_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_proc_sys_reset_0_0/block_design_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_proc_sys_reset_0_0 || ORIG_REF_NAME==block_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_interconnect_1_0/block_design_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_interconnect_1_0 || ORIG_REF_NAME==block_design_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_xlconstant_0_0/block_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_xlconstant_0_0 || ORIG_REF_NAME==block_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_proc_sys_reset_1_0/block_design_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_proc_sys_reset_1_0 || ORIG_REF_NAME==block_design_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_xbar_0/block_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_xbar_0 || ORIG_REF_NAME==block_design_xbar_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_1/block_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_pc_1 || ORIG_REF_NAME==block_design_auto_pc_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_m01_regslice_0/block_design_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_m01_regslice_0 || ORIG_REF_NAME==block_design_m01_regslice_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_m00_regslice_0/block_design_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_m00_regslice_0 || ORIG_REF_NAME==block_design_m00_regslice_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_0/block_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_pc_0 || ORIG_REF_NAME==block_design_auto_pc_0} -quiet] -quiet

# XDC: bd/block_design/block_design_ooc.xdc
